import './globals.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import Home from './page';
import path from 'path';
import fsPromises from 'fs/promises';
import { IFlights } from '@/interfaces/flight.interface';
import transformData from '@/api/transformData';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Frontend-test',
  description: 'Generated by create next app',
};

async function getData() {
  const resJson = await fsPromises.readFile(path.join(process.cwd(), 'api/flights.json'));
  const res: IFlights = JSON.parse(resJson.toString());
  return res;
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const rawData = await getData();
  const data = transformData(rawData);
  return (
    <html lang="en">
      <body className={inter.className}>
        <Home data={data} />
      </body>
    </html>
  )
};
